# -*- coding: utf-8 -*-
"""sistema bancário.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbVAODC8H0-xaozkwzTpbrvnZL35So6J
"""

"""Sistema Bancário """

# Variáveis principais
saldo = 0.0
limite = 500
numero_saques = 0
LIMITE_SAQUES = 3
movimentacoes = []  # lista para registrar as operações


def depositar(valor):
    global saldo
    if valor > 0:
        saldo += valor
        movimentacoes.append(f"Depósito: R$ {valor:.2f}")
        print(f"Depósito de R$ {valor:.2f} realizado com sucesso!")
    else:
        print("Operação falhou! Valor inválido.")


def sacar(valor):
    global saldo, numero_saques
    if valor > saldo:
        print("Operação falhou! Saldo insuficiente.")
    elif valor > limite:
        print("Operação falhou! O valor do saque excede o limite.")
    elif numero_saques >= LIMITE_SAQUES:
        print("Operação falhou! Número máximo de saques atingido.")
    elif valor > 0:
        saldo -= valor
        numero_saques += 1
        movimentacoes.append(f"Saque: R$ {valor:.2f}")
        print(f"Saque de R$ {valor:.2f} realizado com sucesso!")
    else:
        print("Operação falhou! Valor inválido.")


def exibir_extrato():
    print("\n=========== EXTRATO ===========")
    if movimentacoes:
        for mov in movimentacoes:
            print(mov)
    else:
        print("Não foram realizadas movimentações.")
    print(f"\nSaldo: R$ {saldo:.2f}")
    print("=================================")


def menu():
    return input("""
[d] Depositar
[s] Sacar
[e] Extrato
[q] Sair

=> """)


# Loop principal
while True:
    opcao = menu()

    if opcao == "d":
        valor = float(input("Informe o valor do depósito: "))
        depositar(valor)

    elif opcao == "s":
        valor = float(input("Informe o valor do saque: "))
        sacar(valor)

    elif opcao == "e":
        exibir_extrato()

    elif opcao == "q":
        print("Saindo do sistema... Obrigado!")
        break

    else:
        print("Operação inválida! Selecione novamente.")